language: go

go:
- "1.12"
- tip


sudo: required
cache:
  directories:
  - "daptinweb/node_modules"

services:
- docker

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- ls -lah
- nvm install v13.6.0
- node -v && npm -v
- cat .travis.yml
- "echo 'mode: set' > c.out"
- go get -t ./...
- go test ./... -coverpkg github.com/daptin/daptin/... -coverprofile=coverage.txt -covermode=atomic
- ls -lah
- go get github.com/GeertJohan/go.rice/rice
- ls -lah
- go get github.com/karalabe/xgo
- go get
- cd daptinweb
- pwd
- npm install -g @quasar/cli
- npm install && npm rebuild node-sass
- npm run build
- cd ..
- pwd
- rice embed-go
- ls -lah
- GOOS=linux go build  -a -ldflags '-extldflags "-static"' -o main
- mkdir docker_dir
- cp ./main ./docker_dir/main
- cp Dockerfile docker_dir/Dockerfile


after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  cp Dockerfile docker_dir/Dockerfile && cd docker_dir && docker build -t daptin/daptin:travis . && cd ..;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push daptin/daptin:travis;
  fi
- bash <(curl -s https://codecov.io/bash)
- cat /home/travis/gopath/src/github.com/daptin/daptin/coverage.txt
- bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

notifications:
  email: false
