test_with_go_modules: &test_with_go_modules
  steps:
  - checkout
  - run: go test ./...
  - run: go vet ./...

test_without_go_modules: &test_without_go_modules
  working_directory: /go/src/github.com/daptin/daptin
  steps:
  - checkout
  - run: go get -v -t -d ./...
  - run: go test ./...
  - run: go vet ./...

defaults: &defaults
  <<: *test_with_go_modules

version: 2
jobs:
  golang:1.8.7:
    <<: *test_without_go_modules
    docker:
    - image: circleci/golang:1.8.7
  golang:1.9.7:
    <<: *test_without_go_modules
    docker:
    - image: circleci/golang:1.9.7
  golang:1.11:
    <<: *defaults
    docker:
    - image: circleci/golang:1.11
  golang:latest:
    <<: *defaults
    docker:
    - image: circleci/golang:latest
  coveralls:
    docker:
    - image: circleci/golang:latest
    steps:
    - checkout
    - run: go get github.com/daptin/daptin
    - run: go test -v -cover -race -coverprofile=coverage.out
    - run: /go/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken MaRVNq4KGrGW11NELIp9kniu2d5P2kt0s

workflows:
  version: 2
  build:
    jobs:
    - golang:1.8.7
    - golang:1.9.7
    - golang:1.11
    - golang:latest
    - coveralls