version: '2'

services:
  daptin:
    image: daptin/daptin
    container_name: daptin
    restart: always
    ports:
      - "8090:8080"
    environment:
      - DAPTIN_DB_TYPE=mysql
      - DAPTIN_DB_CONNECTION_STRING=devsuser:devspassword@tcp(daptinmysqldb:3306)/devsupport
      - PORT=8080
      - DAPTIN_PORT=8080
    links:
      - daptinmysqldb:daptinmysqldb
    depends_on:
      - "daptinmysqldb"
    networks:
      - my_net
  daptinmysqldb:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=devsupport
      - MYSQL_ROOT_PASSWORD=devrootsupport
      - MYSQL_USER=devsuser
      - MYSQL_PASSWORD=devspassword
    networks:
      - my_net
networks:
  my_net:
    external:
      name: my_net